
set cindent      "使用 C 风格的自动缩进
set expandtab    "将 Tab 扩展成空格
set number       "设置显示行号
set shiftwidth=2 "设置自动缩进的宽度
set tabstop=2    "设置 Tab 所占的宽度

"对行末的空格标红
highlight WhitespaceEOL ctermbg=red guibg=red
match WhitespaceEOL /\s\+$/

autocmd BufWritePre * :%s/\s\+$//e " 自动去除行尾的空格

"vim 保存时，自动格式化 C/C++ 代码
function! Formatonsave()
  let l:lines = "all"
  py3f /usr/share/vim/addons/syntax/clang-format.py
endfunction

autocmd BufWritePre *.h,*.cc,*.cpp,*.c call Formatonsave()

