language: cpp
sudo: required
jobs:
  include:
    - stage: "test Ubuntu 14.04 TLS"
      dist: trusty
      compiler: clang
    - dist: trusty
      compiler: gcc
    - stage: "test Ubuntu 16.04 TLS"
      dist: xenial
      compiler: clang
    - dist: xenial
      compiler: gcc
install:
  - ./scripts/install-dependencies.sh
before_script:
  - ./scripts/before-build.sh
script:
  - ./scripts/build.sh

